server:
  port: 40002

logging:
  level:
    root: info
    #    org.springframework.security.web: debug
    org.springframework.security.web.FilterChainProxy: debug #过滤器执行顺序
    org.springframework.security.web.access.expression.ExpressionBasedFilterInvocationSecurityMetadataSource: info #权限配置
    org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource: info #权限配置
    org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration: debug
spring:
  security:
    user:
      name: lph
      password: 123456

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 426218107liuf
    platform: mysql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
